[params.plausible]
   enable = true
   # --- MANDATORY Domain name
   domain = "blog.rodrcastro.com"
   # --- Outboundlink goal
   # outbound_link = false
   # --- Track donwloaded files
   # file_downloads = true
   # file_downloads_types = "sh,run"
   # --- Manage Adblockers
   # custom_js_domain = "stats.mydomain.org"   # Deprecated -> please use proxying
   # proxy_netlify = false
   # --- Self hosting
   selfhosted_domain = "plausible.rodrcastro.dev"
   # --- Write public dashboard url in source
   # public_dashboard = true
   # --- For embeded dashboard
   # dash_disable = false
   # dash_link = "https://plausible.io/share/yourdomain?auth=AZE1234RTYUOP67"
   # dash_theme = ""
   # dash_bgcolor = ""
   # -- debug mode
   debug = true
   # -- remove console tip for giving a star on github
   gitstar = false
[params.plausible_version]
   id = "1.17.2"
